### ISSUE TITLE
🌱 Enable layerValidation by default

### ISSUE THREAD

**Issue by TylerGillson** [validator-labs/validator-plugin-oci#235]
### Summary

OCIValidator YAML files are too duplicative, e.g.:
```
apiVersion: validation.spectrocloud.labs/v1alpha1
kind: OciValidator
metadata:
  name: oci-validator-4-4-11
spec:
  ociRegistryRules:
  - name: gcr-io-4-4-11
    host: gcr.io
    artifacts:
    - ref: gcr.io/spectro-images-public/release/kubevirt/virt-api:v1.2.0
      layerValidation: true
    - ref: gcr.io/spectro-images-public/release/kubevirt/virt-controller:v1.2.0
      layerValidation: true
    - ref: gcr.io/spectro-images-public/release/kubevirt/virt-exportproxy:v1.2.0
      layerValidation: true
    - ref: gcr.io/spectro-images-public/release/kubevirt/virt-handler:v1.2.0
      layerValidation: true
    - ref: gcr.io/spectro-images-public/release/kubevirt/virt-launcher:v1.2.0
      layerValidation: true
    - ref: gcr.io/spectro-images-public/release/kubevirt/virt-operator:v1.2.0
      layerValidation: true
    - ref: gcr.io/spectro-images-public/release/snapshot-controller/alpine:3.19.1
      layerValidation: true
    - ref: gcr.io/spectro-images-public/release/spectro-cleanup
```
Therefore we should enable layerValidation by default.

Additionally, it should be configurable at the rule level (outside individual artifacts). Any artifact level configuration would override the global default.
